export enum LaunchState {
  IDLE = "IDLE",
  INPUT_ACTIVE = "INPUT_ACTIVE",
  HI_SUBMITTED = "HI_SUBMITTED",
  HI_TRANSFORMING = "HI_TRANSFORMING",
  SIGN_ACTIVE = "SIGN_ACTIVE",
  SIGN_COMPLETE = "SIGN_COMPLETE",
  LOGO_REVEAL = "LOGO_REVEAL",
  LOGO_HOLD = "LOGO_HOLD",
  IDENTITY_REVEAL = "IDENTITY_REVEAL",
  IDENTITY_HOLD = "IDENTITY_HOLD",
  WEBSITE_REVEAL = "WEBSITE_REVEAL",
  EXPERIENCE_COMPLETE = "EXPERIENCE_COMPLETE"
}

export type LaunchContextType = {
  currentState: LaunchState;
  setState: (state: LaunchState) => void;
};
